# ascii_art = '''
#                                   _._
#                                .-~ | ~-.
#                                |   |   |
#                                |  _:_  |                    .-:~--.._
#                              .-"~~ | ~~"-.                .~  |      |
#             _.-~:.           |     |     |                |   |      |
#            |    | `.         |     |     |                |   |      |
#   _..--~:-.|    |  |         |     |     |                |   |      |
#  |      |  ~.   |  |         |  __.:.__  |                |   |      |
#  |      |   |   |  |       .-"~~   |   ~~"-.              |   |      |
#  |      |   |  _|.--~:-.   |       |       |         .:~-.|   |      |
#  |      A   | |      |  ~. |       |   _.-:~--._   .' |   |   |      |
#  |      M   | |      |   | |       |  |   |     |  |  |   |   |      |
#  |      C   | |      |   | |       |  |   |     |  |  |   |   |      |
#  |      |   | |      |   | |       |  |   |     |  |  |   |   |      |
#  |      9   | |      |   | |       |  |   |     |  |  |   |   |      |
#  |      9   | |      |   | |       |  |   |     |  |  |   |   |      |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# '''
# ascii_art = '''

                  # _________-----_____
       # _____------           __      ----_
# ___----             ___------              \
   # ----________        ----                 \
               # -----__    |             _____)
                    # __-                /     \
        # _______-----    ___--          \    /)\
  # ------_______      ---____            \__/  /
               # -----__    \ --    _          /\
                      # --__--__     \_____/   \_/\
                              # ----|   /          |
                                  # |  |___________|
                                  # |  | ((_(_)| )_)
                                  # |  \_((_(_)|/(_)
                                  # \             (
                                   # \_____________)
# '''


[colors]
title = "cyan"
